// работа с файлами данного типа доступна только в intellij idea версии ultimate
// как и прямая работа с базой данных (я про отсутствие справа меню database)

GET http://localhost:8080/users

###
POST http://localhost:8080/user
Content-Type: application/json

{"phoneNumber": "88005553535", "money": 4500}

###
POST http://localhost:8080/user
Content-Type: application/json

{"phoneNumber": "89003332211", "money": 100}

###
POST http://localhost:8080/user
Content-Type: application/json

{"phoneNumber": "89990005522", "money": 100}
###
GET http://localhost:8080/user/e09b347c-0a32-4b40-b9f2-8baa7b22f542

###
PUT http://localhost:8080/user
Content-Type: application/json

{"id": "e09b347c-0a32-4b40-b9f2-8baa7b22f542", "phoneNumber": "+7(999)000-55-22"}

###
DELETE http://localhost:8080/user/e1a792fc-deb0-41be-83ea-ca9650621f01

###
PUT http://localhost:8080/user/money/refill
Content-Type: application/json

{"id": "e09b347c-0a32-4b40-b9f2-8baa7b22f542", "money": 100}

###
PUT http://localhost:8080/user/money/withdraw
Content-Type: application/json

{"id": "e09b347c-0a32-4b40-b9f2-8baa7b22f542", "money": 100}

###
PUT http://localhost:8080/transaction
Content-Type: application/json

{"senderId": "77acdf99-8ee1-4197-a673-502ad8b722bd", "recipientId": "e09b347c-0a32-4b40-b9f2-8baa7b22f542",
  "money": 1000, "category": 0}

###
PUT http://localhost:8080/transaction
Content-Type: application/json

{"senderId": "e09b347c-0a32-4b40-b9f2-8baa7b22f542", "recipientId": "77acdf99-8ee1-4197-a673-502ad8b722bd",
  "money": 1000, "category": 4}